// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyndzkgsyvdexqlmiman.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5bmR6a2dzeXZkZXhxbG1pbWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDczOTEsImV4cCI6MjA2NDcyMzM5MX0.3We1UwrhouJtyCGpsH7pihYxrtJ8E50s0JiJf2O1lRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);